
.npm-pkg:
  image: "node:14"
  stage: deploy
  before_script:
    - if [[ "${WORKDIR}" ]]; then cd $WORKDIR; fi
    - npm install && npm ci --cache .npm --prefer-offline
    - |
      {
        echo "@krpc:registry=${CI_API_V4_URL}/projects/9/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/9/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee --append .npmrc
  script:
    - npm publish

    
